# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gameUi2.ui'
#
# Created: Mon Jul 13 21:52:17 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 865)
        font = QtGui.QFont()
        font.setFamily("Saab")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ctrlBox = QtGui.QGroupBox(self.centralwidget)
        self.ctrlBox.setGeometry(QtCore.QRect(0, 0, 231, 711))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(232, 147, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 232, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 235, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 147, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 232, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 235, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 147, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 232, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 235, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 235, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ctrlBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Saab")
        font.setPointSize(16)
        self.ctrlBox.setFont(font)
        self.ctrlBox.setTitle("")
        self.ctrlBox.setObjectName("ctrlBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.ctrlBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(0, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.line_8 = QtGui.QFrame(self.ctrlBox)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_2.addWidget(self.line_8)
        self.line_12 = QtGui.QFrame(self.ctrlBox)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_2.addWidget(self.line_12)
        spacerItem2 = QtGui.QSpacerItem(0, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.startButton = QtGui.QPushButton(self.ctrlBox)
        font = QtGui.QFont()
        font.setFamily("Saab")
        font.setPointSize(17)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_2.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(self.ctrlBox)
        font = QtGui.QFont()
        font.setFamily("Saab")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_2.addWidget(self.stopButton)
        spacerItem4 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(0, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem5)
        self.line_7 = QtGui.QFrame(self.ctrlBox)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.line = QtGui.QFrame(self.ctrlBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        spacerItem7 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bkButton = QtGui.QPushButton(self.ctrlBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bkButton.setFont(font)
        self.bkButton.setObjectName("bkButton")
        self.horizontalLayout_2.addWidget(self.bkButton)
        self.line_9 = QtGui.QFrame(self.ctrlBox)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_2.addWidget(self.line_9)
        self.fwdButton = QtGui.QPushButton(self.ctrlBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fwdButton.setFont(font)
        self.fwdButton.setObjectName("fwdButton")
        self.horizontalLayout_2.addWidget(self.fwdButton)
        self.line_13 = QtGui.QFrame(self.ctrlBox)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_2.addWidget(self.line_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        spacerItem9 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem9)
        self.line_3 = QtGui.QFrame(self.ctrlBox)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.line_11 = QtGui.QFrame(self.ctrlBox)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_2.addWidget(self.line_11)
        spacerItem10 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem10)
        self.tickLabel = QtGui.QLabel(self.ctrlBox)
        font = QtGui.QFont()
        font.setFamily("Saab")
        font.setPointSize(16)
        self.tickLabel.setFont(font)
        self.tickLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tickLabel.setObjectName("tickLabel")
        self.verticalLayout_2.addWidget(self.tickLabel)
        self.tickTimeInput = QtGui.QDoubleSpinBox(self.ctrlBox)
        font = QtGui.QFont()
        font.setFamily("Saab")
        font.setPointSize(16)
        self.tickTimeInput.setFont(font)
        self.tickTimeInput.setDecimals(2)
        self.tickTimeInput.setMinimum(0.02)
        self.tickTimeInput.setMaximum(5.0)
        self.tickTimeInput.setSingleStep(0.1)
        self.tickTimeInput.setProperty("value", 0.4)
        self.tickTimeInput.setObjectName("tickTimeInput")
        self.verticalLayout_2.addWidget(self.tickTimeInput)
        spacerItem11 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem11)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.line_5 = QtGui.QFrame(self.ctrlBox)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.line_6 = QtGui.QFrame(self.ctrlBox)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        spacerItem14 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem14)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtGui.QLabel(self.ctrlBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.randFillInput = QtGui.QSpinBox(self.ctrlBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.randFillInput.setFont(font)
        self.randFillInput.setProperty("value", 36)
        self.randFillInput.setObjectName("randFillInput")
        self.verticalLayout_3.addWidget(self.randFillInput)
        self.randFillBtn = QtGui.QPushButton(self.ctrlBox)
        self.randFillBtn.setObjectName("randFillBtn")
        self.verticalLayout_3.addWidget(self.randFillBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem15 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem15)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem16)
        self.line_2 = QtGui.QFrame(self.ctrlBox)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.line_14 = QtGui.QFrame(self.ctrlBox)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_2.addWidget(self.line_14)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        spacerItem18 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem18)
        self.resetButton = QtGui.QPushButton(self.ctrlBox)
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout_2.addWidget(self.resetButton)
        spacerItem19 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem19)
        self.line_4 = QtGui.QFrame(self.ctrlBox)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.line_10 = QtGui.QFrame(self.ctrlBox)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 10, 851, 751))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem20 = QtGui.QSpacerItem(0, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem20)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem21 = QtGui.QSpacerItem(1, 0, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem21)
        self.boardGrid = QtGui.QGridLayout()
        self.boardGrid.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.boardGrid.setObjectName("boardGrid")
        self.horizontalLayout.addLayout(self.boardGrid)
        spacerItem22 = QtGui.QSpacerItem(1, 0, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem22)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem23 = QtGui.QSpacerItem(0, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem23)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 43))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.statusBar.setFont(font)
        self.statusBar.setToolTip("")
        self.statusBar.setAutoFillBackground(True)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Start running Conway game (auto)", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "pause", None, QtGui.QApplication.UnicodeUTF8))
        self.bkButton.setText(QtGui.QApplication.translate("MainWindow", "<- prev", None, QtGui.QApplication.UnicodeUTF8))
        self.fwdButton.setText(QtGui.QApplication.translate("MainWindow", "next ->", None, QtGui.QApplication.UnicodeUTF8))
        self.tickLabel.setText(QtGui.QApplication.translate("MainWindow", "game speed", None, QtGui.QApplication.UnicodeUTF8))
        self.tickTimeInput.setSuffix(QtGui.QApplication.translate("MainWindow", " sec/tick", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", " random fill cells:", None, QtGui.QApplication.UnicodeUTF8))
        self.randFillBtn.setText(QtGui.QApplication.translate("MainWindow", "random fill", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("MainWindow", "Reset/Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.statusBar.setStatusTip(QtGui.QApplication.translate("MainWindow", "Press start to run (auto) or use prev & next buttons (manual)", None, QtGui.QApplication.UnicodeUTF8))

